export enum ACTIONS {
    CREATE_ROW = 'CREATE_ROW',
    UPDATE_ROW = 'UPDATE_ROW',
    ADD_COMBINATION = 'ADD_COMBINATION',
    REMOVE_COMBINATION = 'REMOVE_COMBINATION',
    RESET_COMBINATION = 'RESET_COMBINATION'
}